#!/bin/bash
echo "script name: $0"
echo "first argument: $1"
echo "second argument: $2"
echo "third argument: $3"
echo "total number of arguments: $#"
echo "all arguments: $*"
echo "all arguments: $@"
echo "process id of the current script: $$"
echo "last command exit status: $?"
echo "last background process id: $!"
echo "current shell: $SHELL"
echo "home directory: $HOME"
echo "current user: $USER"
echo "current working directory: $PWD"
echo "script execution started at: $(date)"
echo "script execution started at: $(date +%Y-%m-%d-%H:%M:%S)"
echo "Goodbye!"
echo "script name without path: $(basename "$0")"
echo "script directory: $(dirname "$0")"
echo "number of CPU cores: $(nproc)"
echo "total memory in MB: $(free -m | awk '/^Mem:/ {print $2}')"
echo "available disk space in GB: $(df -h / | awk 'NR==2 {print $4}')"
echo "current date and time: $(date '+%Y-%m-%d %H:%M:%S')"
echo "uptime: $(uptime -p)"
echo "last login of current user: $(last -n 1 $USER)"
echo "network interfaces: $(ip -o -4 addr show | awk '{print $2, $4}')"
echo "environment variables:"
printenv
echo "Goodbye!"