name: Node.js CI Pipeline
on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        #step 1
      - name: Checkout repository
        uses: actions/checkout@v5
        #step 2
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
        #step 3
      - name: Install dependencies
        run: npm ci
#step 4
      - name: Build
        run: npm run build --if-present
#step 5
      - name: Test
        run: npm test